version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    env_file: .env
    environment:
      - DATABASE_URL=postgres://postgres@db/bad_db
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_DB=bad_db
